adding SFR test cases
neams-th-coe/cardinal_amr pull request #12
Opened 2024-11-08 16:37 UTC by magnoxemo

2025-02-21 20:29 UTC, lewisgross1296 requested changes
A few things that can be applied throughout. Try and look for repeated code that could be turned into functions.

Also, you should probably remove the .jitcache (not something you need or should even version).

Worth considering doing this PR as a few other ones (for the various assemblies).

2025-02-21 20:29 UTC, lewisgross1296 commented on SFR/Assembly/inner_assembly/make_SFR_assembly_model.py
> +###################################################################
Let's consider making a function that returns a dictionary of materials `create_SFR_materials()` and converting use of the material objects to material_dict["mat_name"]

2025-02-21 20:29 UTC, lewisgross1296 commented on SFR/Assembly/inner_assembly/mesh.i
> +                0  0  0  0  0  0  0  0  0 '
I personally like to use one space between the entries in the pattern. This looks a little wonky (though I'm sure it generates the correct mesh.

2025-02-21 20:29 UTC, lewisgross1296 commented on SFR/Assembly/inner_assembly/make_SFR_assembly_model.py
> +cladding_material = openmc.Material.mix_materials([cu63,Al2O3], [0.997,0.003], 'wo')
Probably applicable other places, but we should maybe Black format your python code

2025-02-21 20:29 UTC, lewisgross1296 commented on SFR/Assembly/inner_assembly/make_SFR_assembly_model.py
> +clad_or = openmc.ZCylinder(surface_id=3, r=1.073/2)
Not sure you need these `surface_id`s here. Also we should probably use variables to define the radii

2025-02-21 20:29 UTC, lewisgross1296 commented on SFR/Assembly/inner_assembly/make_SFR_assembly_model.py
> +shannon_entropy=arguments.shannon_entropy
let's do this in a ``main()`` function and throw a 
```
if __name__ == "__main__":
    main()
```
at the bottom.

I think a function like `build_SFR_model()` that actually does all the model generation should be called form `main()`

2025-02-21 20:29 UTC, lewisgross1296 commented on SFR/Assembly/inner_assembly/make_SFR_assembly_model.py
> +settings.export_to_xml()
we can make a settings function too

2025-02-21 20:29 UTC, lewisgross1296 commented on SFR/Assembly/inner_assembly/mesh.i
> +#----------------------------------------------------------------------------------------
would be nice to have a `common_input.i` and 
```
!include common_input.i
```
at the top

2025-02-21 20:29 UTC, lewisgross1296 commented on SFR/Assembly/outer_assembly/make_SFR_assembly_model.py
> +out_lat.outer = sodium_mod_u
consider using a 3D lattice, you can look at the GCMR repo to see an example of how to do this and still have density feedback

2025-02-26 01:18 UTC, aprilnovak commented on SFR/Assembly/inner_assembly/make_SFR_assembly_model.py
> +ap.add_argument('-n', dest='n_axial', type=int, default=100, help='Number of cells in the Z direction')
How about a default of 1? I think that makes sense as a default because that would be the best performance choice if not needing extra cells for depletion/feedback.

2025-02-26 01:19 UTC, aprilnovak commented on SFR/Assembly/inner_assembly/make_SFR_assembly_model.py
> +inner_fuel_material= openmc.Material.mix_materials([u235, u238, pu238, pu239, pu240, pu241, pu242, am241, o16],[0.0019, 0.7509, 0.0046, 0.0612, 0.0383, 0.0106, 0.0134, 0.001, 0.1181],'wo')
This would be much more efficient to create this object using a single `openmc.Material` (as long as you know the overall fuel density from somewhere?)

2025-02-26 01:20 UTC, aprilnovak commented on SFR/Assembly/inner_assembly/make_SFR_assembly_model.py
> +    layer=+z_plane[i]&-z_plane[i+1]
This may have been from an example, but why not use a lattice in the z-direction? I would expect the tracking performance to be a little bit better that way, as opposed to N unique cells.

2025-02-26 01:21 UTC, aprilnovak commented on SFR/Assembly/inner_assembly/mesh.i
> +      num_sides = 6 #determine if that will be a square or hexagon=6
this will be a hexagon, so I think the comment can be removed

2025-02-26 01:22 UTC, aprilnovak commented on SFR/Assembly/inner_assembly/mesh.i
> +        top_boundary = '10000'
I know the reactor module likes to use the sideset 10000 as the default outer boundary (if my memory is correct). Did you check that there's not any other existing sidesets numbered 10000 that might be conflicting with this one?

2025-02-26 01:22 UTC, aprilnovak commented on SFR/Assembly/inner_assembly/openmc.i
> +[Adaptivity]
Because we may want to run a whole series of models through different AMR strategies, can you please update these .i files to use the `!include strategy` idea from #1?

2025-02-26 01:46 UTC, gonuke commented
In general, I encourage you to look at the changes that @nuclearkevin made during review to the LWR cases and see how you would make changes to match the design patterns used there.

2025-02-26 01:49 UTC, gonuke commented
The `*.so` files shouldn't be here.  You might want to update the `.gitignore` and get used to adding files explicitly to each commit rather than `git add -A` (or other shortcuts that can risk adding too many files)

2025-02-26 01:56 UTC, lewisgross1296 commented on SFR/Assembly/inner_assembly/make_SFR_assembly_model.py
> +    layer=+z_plane[i]&-z_plane[i+1]
Agreed. Check out my GCMR [code](https://github.com/cnerg/gcmr/blob/7b7f7785f7aeb0068c279975434c76f0c138196b/depletion_standalone/inf_assemblies/make_gcmr_model.py#L158) for an example with a 3D lattice. There might be some depletion things you don't need in there but it should serve as a good base. IIRC there's some cardinal tutorials that do it too

2025-02-26 01:58 UTC, gonuke commented on SFR/Assembly/inner_assembly/make_SFR_assembly_model.py
> +    layer=+z_plane[i]&-z_plane[i+1]
This may be based on the approach that @nuclearkevin  used for LWR problems?

2025-02-28 15:14 UTC, magnoxemo commented on SFR/Assembly/inner_assembly/mesh.i
> +        top_boundary = '10000'
Thank you April. I removed that default top and bottom name and generated the mesh again which I think looks OK. But I hope someone else could cross check maybe?

2025-02-28 17:28 UTC, magnoxemo commented on SFR/Assembly/inner_assembly/openmc.i
> +[Adaptivity]
All the amr studies I have for the SFR models are direct implementation of Kevin's [value_jump_rel_error](https://github.com/neams-th-coe/cardinal_amr/blob/main/amr_strategies/value_jump_rel_error.i). I can remove  the adaptivity block from my SFR models since [value_jump_rel_error](https://github.com/neams-th-coe/cardinal_amr/blob/main/amr_strategies/value_jump_rel_error.i) already does it?

2025-02-28 17:56 UTC, lewisgross1296 commented on SFR/Assembly/inner_assembly/openmc.i
> +[Adaptivity]
I think April is referring to this https://github.com/neams-th-coe/cardinal_amr/blob/221a7f18b78729e39b9b7bf48e035ed427009a56/README.md?plain=1#L20-L25

2025-02-28 18:51 UTC, magnoxemo commented
I think this is ready for second round of review .

2025-03-03 13:43 UTC, gonuke requested changes
Here's a first round of reviews...

2025-03-05 17:54 UTC, lewisgross1296 requested changes
Couple of places with magic numbers, didn't mark them all. Def check the PatterenedHexMeshGenerator [docs](https://mooseframework.inl.gov/source/meshgenerators/PatternedHexMeshGenerator.html) to make sure your hexagon size is as intended

2025-03-05 17:54 UTC, lewisgross1296 commented on SFR/Assembly/outer_assembly/mesh.i
> +         hexagon_size = '${fparse edge_length}'
You might need to specify `hexagon_size_style` here. IIRC the [default](https://mooseframework.inl.gov/source/meshgenerators/PatternedHexMeshGenerator.html) is `apothem` (in which case you'd give one half the flat to flat distance), but I think you'd want to use `radius` if you're supplying `edge_length`

2025-03-05 17:54 UTC, lewisgross1296 commented on SFR/Assembly/inner_assembly/mesh.i
> +         hexagon_size = '${fparse edge_length}'
same here

2025-03-05 17:54 UTC, lewisgross1296 commented on SFR/inner_fuel_pincell/make_SFR_pincell_model.py
> +    pitch = 1.25984
I think it would be worth considering setting a default for shannon_entropy and checking/raising an exception to make sure height is provided and positive.

pitch is a magic number here

2025-03-05 17:54 UTC, lewisgross1296 commented on SFR/inner_fuel_pincell/make_SFR_pincell_model.py
> +        "tolerance": 1000.0,
Is there a reason you set a temperature tolerance with inerpolation? I'm not sure using a value of 1000 would provide good behavior

2025-03-05 17:54 UTC, lewisgross1296 commented on SFR/inner_fuel_pincell/make_SFR_pincell_model.py
> +from materials import *
is this necessary?

2025-03-05 17:54 UTC, lewisgross1296 commented on SFR/Assembly/outer_assembly/make_SFR_assembly_model.py
> +    in_lat.pitch = (21.08 / 17,)
magic numbers

2025-03-05 17:54 UTC, lewisgross1296 commented on SFR/Assembly/outer_assembly/make_SFR_assembly_model.py
> +    bottom.boundary_type = "vacuum"
I think you might be able to only define the top/bottom planes if you convert to a 3D lattice (assuming there's one cell containing the entire 3D lattice inside a hexagonal prism)

2025-03-05 17:54 UTC, lewisgross1296 commented on SFR/Assembly/outer_assembly/make_SFR_assembly_model.py
> +    )
I know black probably left the middle argument as is, but it might be nice to manually format it to match the appearance of the others

2025-03-09 19:43 UTC, magnoxemo commented on SFR/inner_fuel_pincell/make_SFR_pincell_model.py
> +        "tolerance": 1000.0,
Ig we don't need that here at all as we aren't not doing multiphysics yet. I can just get rid of it.

2025-03-09 20:57 UTC, magnoxemo commented
I tried to address all the suggestions since this branch is too messy with commit history

2025-03-09 21:07 UTC, magnoxemo commented
I think this is ready for 2nd round of review

2025-03-18 03:34 UTC, gonuke requested changes
There are many places where I recommend substantial reuse.  In general, I recommend a careful look at the final version of the LWR examples and revising accordingly.

2025-03-18 03:34 UTC, gonuke commented on SFR/materials.py
> +        )
I don't see it used often, but have learned about [`add_components`](https://docs.openmc.org/en/stable/pythonapi/generated/openmc.Material.html#openmc.Material.add_components) - could we use that here?

2025-03-18 03:34 UTC, gonuke commented on SFR/outer_fuel_pincell/make_SFR_pincell_model.py
> +    upper_right = (pitch / 2, pitch / 2, height)
```suggestion
    half_pitch = geom.pitch / 2.0
    lower_left = (-half_pitch, -half_pitch, 0.0)
    upper_right = (half_pitch, half_pitch, height)
```

2025-03-18 03:34 UTC, gonuke commented on SFR/outer_fuel_pincell/make_SFR_pincell_model.py
> +    arguments = ap.parse_args()
remove duplicate line

2025-03-18 03:34 UTC, gonuke commented on SFR/outer_fuel_pincell/make_SFR_pincell_model.py
> +    pitch = geom.pitch
If you are using `pitch` directly from `geom`, why not use `height` as well, instead of passing it as an argument?

2025-03-18 03:34 UTC, gonuke commented on SFR/outer_fuel_pincell/make_SFR_pincell_model.py
> +    height = geom.height
You don't really use this enough to assign a new variable - just use `geom.height` where necessary

2025-03-18 03:34 UTC, gonuke commented on SFR/outer_fuel_pincell/make_SFR_pincell_model.py
> +    z_plane = [openmc.ZPlane(z0=i) for i in np.linspace(-height / 2, height / 2, N + 1)]
```suggestion
    z_plane = [openmc.ZPlane(z0=i) for i in np.linspace(-geom.height / 2, geom.height / 2, N + 1)]
```

2025-03-18 03:34 UTC, gonuke commented on SFR/outer_fuel_pincell/make_SFR_pincell_model.py
> +        )
See [this](https://github.com/neams-th-coe/cardinal_amr/blob/221a7f18b78729e39b9b7bf48e035ed427009a56/models/lwr/pincell/make_openmc_model.py#L37) in the LWR models for a cleaner solution

2025-03-18 03:34 UTC, gonuke commented on SFR/outer_fuel_pincell/make_SFR_pincell_model.py
> +    settings(shannon_entropy=False, height=height)
Don't you want to use your argument for `shannon_entropy`?

2025-03-18 03:34 UTC, gonuke commented on SFR/outer_fuel_pincell/mesh.i
> +    background_block_names = 'water'
Do you have any water in this SFR?

2025-03-18 03:34 UTC, gonuke commented on SFR/inner_fuel_pincell/mesh.i
Is this different from the `outer_fuel_pincell` version?

2025-03-18 03:34 UTC, gonuke commented on SFR/inner_fuel_pincell/openmc.i
Is this different from the `outer_fuel_pincell` version?

2025-03-18 03:34 UTC, gonuke commented on SFR/inner_fuel_pincell/make_SFR_pincell_model.py
This looks the same as the `outer_fuel_pincell` version but without its improvements - a perfect example of why there should be a single file used in each place, perahps by symlink

2025-03-18 03:34 UTC, gonuke commented on SFR/Assembly/outer_assembly/mesh.i
> +
include the mesh file for the outer pincells and reuse that information (see LWR examples)

2025-03-18 03:34 UTC, gonuke commented on SFR/Assembly/outer_assembly/make_SFR_assembly_model.py
> +        ring_list.append(ring)
```suggestion
    ring_list = [ [universe] * max(ring-1, 1) * 6 for ring in range(number_of_rings, 0, -1) ]
```

2025-03-18 03:34 UTC, gonuke commented on SFR/Assembly/outer_assembly/make_SFR_assembly_model.py
This can probably reuse/import things from the `outer_fuel_pincell` version (whereI commented already)

2025-06-06 13:37 UTC, gonuke requested changes
Let's remove the rest of the Assembly files, too

2025-06-06 13:37 UTC, gonuke commented on SFR/Assembly/__in__it.py
This filename doesn't seem right

2025-06-06 13:37 UTC, gonuke commented on SFR/common_input.i
> +pitch        = 1.25984
Please add comments to indicate the units of each quantity

2025-06-06 13:37 UTC, gonuke commented on SFR/materials.py
> +            "Al27": 0.00368012742633955,
Seems like too many significant digits?

2025-06-06 13:37 UTC, gonuke commented on SFR/Pincell/make_openmc_model.py
> +    upper_right = (pitch / 2, pitch / 2, height)
```suggestion
    half_pitch = geom.pitch
    lower_left = (-half_pitch, -half_pitch, 0.0)
    upper_right = (half_pitch, half_pitch, height)
```

2025-06-06 13:37 UTC, gonuke commented on SFR/Pincell/make_openmc_model.py
> +                    help=("Material composition of the pincell fuel material"
```suggestion
    ap.add_argument("-p", dest="pincell_type", type=str, choices=["inner", "outer"],
                    default="inner",
                    help=("Material composition of the pincell fuel material"
```

2025-06-10 14:23 UTC, gonuke approved these changes
This looks good to me - thanks for getting this started @magnoxemo .  Let's see if @lewisgross1296 is satisfied with the updates?

2025-06-10 17:02 UTC, lewisgross1296 requested changes
Just out of curiosity, @magnoxemo, have you generated all the XML and meshes and run this? I think we should not merge until it runs and produces expected results. I suspect things may not work as is

2025-06-10 17:02 UTC, lewisgross1296 commented on SFR/common_input.i
> +lattice_pitch = 1.24  # Pitch used in lattice or mesh generation
I think Paul may have mentioned this, but you should be careful with units. I think most MOOSE stuff defaults to SI, but these look like `cm` to me. If you aren't careful, your MOOSE and OpenMC geometries may be off by a factor of 100 and the coupling will not work

2025-06-10 20:18 UTC, magnoxemo commented on SFR/Pincell/openmc.i
> +[]
For single-physics AMR, does it matter whether the solve is steady or transient? But I agree — once we start coupling multiphysics, we would definitely want to move to a transient solve.

2025-06-11 17:18 UTC, magnoxemo commented
everything is working on my computer. @lewisgross1296 is happy with the changes so far. @gonuke if you want, I think it's ready to be merged. 
 
openmc plot : 
![image](https://github.com/user-attachments/assets/5b6433b2-4b67-4c44-9cfc-7727588b6855)

Mesh:
![image](https://github.com/user-attachments/assets/3ea96e49-5f14-435a-a794-c2cabfe0d16e)
![image](https://github.com/user-attachments/assets/f628f21f-1537-4956-9362-b6e9f35ba191)

Adaptivity:

step1: 
![image](https://github.com/user-attachments/assets/cec0c94a-f2a8-443d-a8e4-7ce3b8635d28)
step2:
![image](https://github.com/user-attachments/assets/03d3e0b1-e15e-49b7-ba46-96e43de49baf)

2025-06-11 17:22 UTC, lewisgross1296 approved these changes
Glad to see it's running. I think most of my concerns were for full multiphysics solves, so this is looking good for now. Thanks Walid!

You may want to interactively rebase into fewer commits.

2025-06-11 18:44 UTC, magnoxemo commented
Okay Ig I messed up while rebasing. Let me fix it

2025-06-11 18:47 UTC, closed without merging

2025-06-11 18:49 UTC, magnoxemo commented
I am closing this PR and open a new one. I made couple of bad choices and that messed up really bad.